language: cpp
compiler:
    - gcc
    - clang
notifications:
    email: false
before_install:
    - sudo add-apt-repository ppa:staticfloat/julia-deps -y
    - sudo add-apt-repository ppa:staticfloat/julianightlies -y
    - sudo apt-get update -qq -y
    - sudo apt-get install julia -y
    - sudo apt-get install libgmp-dev
script:
    - julia -e 'Pkg.init(); run(`ln -s $(pwd()) $(Pkg.dir())/`); Pkg.resolve()'
    - julia -e 'Pkg.build("GLPK.jl")'
    - julia -e 'using GLPK; @assert isdefined(:GLPK); @assert typeof(GLPK) === Module'
    - julia test/runtests.jl

branches:
    except:
        - release-0.1
