language: cpp
compiler:
    - clang
notifications:
    email: false
before_install:
    - sudo add-apt-repository ppa:staticfloat/julia-deps -y
    - sudo add-apt-repository ppa:staticfloat/julianightlies -y
    - sudo apt-get update -qq -y
    - sudo apt-get upgrade -y
    - sudo apt-get install julia -y
    - sudo apt-get install libgmp-dev libltdl3-dev
    - git config --global user.name "Travis User"
    - git config --global user.email "travis@example.net"
script:
    - julia -e "Pkg.init()"
    - julia -e "Pkg.add(Pkg.VersionSet(\"BinDeps\", [VersionNumber(0,0,1)]))"
    - mkdir -p ~/.julia/GLPK
    - cp -R ./* ~/.julia/GLPK/
    - julia ~/.julia/GLPK/deps/build.jl
    - julia ~/.julia/GLPK/test/test.jl
branches:
    except:
        - release-0.1
