language: julia
os:
  - linux
  - osx
julia:
  - release
  - nightly
env:
  matrix:
    - CC="gcc"
    - CC="clang"
notifications:
  email: false
sudo: false # use a docker worker
addons:
  apt_packages:
  - libgmp-dev
# uncomment the following lines to override the default test script
#script:
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.build("GLPK"); Pkg.test("GLPK")'
after_success:
  - if [ $TRAVIS_JULIA_VERSION = "nightly" ]; then julia -e 'cd(Pkg.dir("GLPK")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'; fi
branches:
  except:
    - release-0.1
